2025-03-18 01:01:41,880 - PythonTestLogger - ERROR - Test failed for QA5_P9_P10.py on QA5 for test case {'input': '2 2\n3 1\n4 2\n9 10', 'expected': 'x =\n4.0000 -3.0000\n\nRank = 2\nNullity = 0\n', 'type': 'stdin'}

SRNs: P9/P10

Test Type: stdin

Test Input:
2 2
3 1
4 2
9 10

Expected Output:
x =
4.0000 -3.0000

Rank = 2
Nullity = 0


Actual Output:
x =
4.0000 -3.0000

Rank = 2
Nullity = 0
--------------------------------------------------
2025-03-18 01:01:44,173 - PythonTestLogger - ERROR - Test failed for QA6_P11_P12.py on QA6 for test case {'input': '2 2\n1 2\n0 1\n2 1\n2\n3', 'expected': "P' =\n8.0\n3.0\n\nRREF =\n1.0 0.0\n0.0 1.0\n\nT^-1 =\n1.000 -2.000\n0.000 1.000", 'type': 'stdin'}

SRNs: P11/P12

Error:
Traceback (most recent call last):
  File "/Volumes/Aditya SSD/Project/AutomaticPythonTesting/AutomaticPythonTesting/scripts/QA6_P11_P12.py", line 3, in <module>
    from sympy import Matrix
ModuleNotFoundError: No module named 'sympy'


Test Type: stdin

Test Input:
2 2
1 2
0 1
2 1
2
3

Expected Output:
P' =
8.0
3.0

RREF =
1.0 0.0
0.0 1.0

T^-1 =
1.000 -2.000
0.000 1.000
--------------------------------------------------
2025-03-18 01:01:44,453 - PythonTestLogger - ERROR - Test failed for QA6_P11_P12.py on QA6 for test case {'input': '3 3\n3 1 2\n4 2 1\n1 2 3\n3 1\n1\n0\n1\n', 'expected': "P' =\n5.0\n5.0\n4.0\n\nRREF =\n1.0 0.0 0.0\n0.0 1.0 0.0\n0.0 0.0 1.0\n\nT^-1 =\n0.308 0.077 -0.231\n-0.846 0.538 0.385\n0.462 -0.385 0.154", 'type': 'stdin'}

SRNs: P11/P12

Error:
Traceback (most recent call last):
  File "/Volumes/Aditya SSD/Project/AutomaticPythonTesting/AutomaticPythonTesting/scripts/QA6_P11_P12.py", line 3, in <module>
    from sympy import Matrix
ModuleNotFoundError: No module named 'sympy'


Test Type: stdin

Test Input:
3 3
3 1 2
4 2 1
1 2 3
3 1
1
0
1


Expected Output:
P' =
5.0
5.0
4.0

RREF =
1.0 0.0 0.0
0.0 1.0 0.0
0.0 0.0 1.0

T^-1 =
0.308 0.077 -0.231
-0.846 0.538 0.385
0.462 -0.385 0.154
--------------------------------------------------
2025-03-18 01:01:44,732 - PythonTestLogger - ERROR - Test failed for QA6_P11_P12.py on QA6 for test case {'input': '4 4\n2 3 1 4\n1 5 3 2\n4 2 6 5\n3 1 2 3\n4 1\n5\n6\n7\n8', 'expected': "P' =\n67.0\n72.0\n114.0\n59.0\n\nRREF =\n1.0 0.0 0.0 0.0\n0.0 1.0 0.0 0.0\n0.0 0.0 1.0 0.0\n0.0 0.0 0.0 1.0\n\nT^-1 =\n-0.407 0.185 -0.370 1.037\n-0.037 0.259 -0.185 0.185\n-0.148 0.037 0.259 -0.259\n0.519 -0.296 0.259 -0.593\n", 'type': 'stdin'}

SRNs: P11/P12

Error:
Traceback (most recent call last):
  File "/Volumes/Aditya SSD/Project/AutomaticPythonTesting/AutomaticPythonTesting/scripts/QA6_P11_P12.py", line 3, in <module>
    from sympy import Matrix
ModuleNotFoundError: No module named 'sympy'


Test Type: stdin

Test Input:
4 4
2 3 1 4
1 5 3 2
4 2 6 5
3 1 2 3
4 1
5
6
7
8

Expected Output:
P' =
67.0
72.0
114.0
59.0

RREF =
1.0 0.0 0.0 0.0
0.0 1.0 0.0 0.0
0.0 0.0 1.0 0.0
0.0 0.0 0.0 1.0

T^-1 =
-0.407 0.185 -0.370 1.037
-0.037 0.259 -0.185 0.185
-0.148 0.037 0.259 -0.259
0.519 -0.296 0.259 -0.593

--------------------------------------------------
2025-03-18 01:01:45,024 - PythonTestLogger - ERROR - Test failed for QA7_P13_P14.py on QA7 for test case {'input': '3 4\n1 -1 0 0\n0 1 -1 0\n0 0 1 -1', 'expected': 'RREF =\n1.0 0.0 0.0 -1.0\n0.0 1.0 0.0 -1.0\n0.0 0.0 1.0 -1.0\n\nRank = 3\nNullity = 1', 'type': 'stdin'}

SRNs: P13/P14

Error:
Traceback (most recent call last):
  File "/Volumes/Aditya SSD/Project/AutomaticPythonTesting/AutomaticPythonTesting/scripts/QA7_P13_P14.py", line 3, in <module>
    from sympy import Matrix
ModuleNotFoundError: No module named 'sympy'


Test Type: stdin

Test Input:
3 4
1 -1 0 0
0 1 -1 0
0 0 1 -1

Expected Output:
RREF =
1.0 0.0 0.0 -1.0
0.0 1.0 0.0 -1.0
0.0 0.0 1.0 -1.0

Rank = 3
Nullity = 1
--------------------------------------------------
2025-03-18 01:01:45,347 - PythonTestLogger - ERROR - Test failed for QA7_P13_P14.py on QA7 for test case {'input': '3 3\n1 2 3\n4 5 6\n7 8 10', 'expected': 'RREF =\n1.0 0.0 0.0\n0.0 1.0 0.0\n0.0 0.0 1.0\n\nRank = 3\nNullity = 0', 'type': 'stdin'}

SRNs: P13/P14

Error:
Traceback (most recent call last):
  File "/Volumes/Aditya SSD/Project/AutomaticPythonTesting/AutomaticPythonTesting/scripts/QA7_P13_P14.py", line 3, in <module>
    from sympy import Matrix
ModuleNotFoundError: No module named 'sympy'


Test Type: stdin

Test Input:
3 3
1 2 3
4 5 6
7 8 10

Expected Output:
RREF =
1.0 0.0 0.0
0.0 1.0 0.0
0.0 0.0 1.0

Rank = 3
Nullity = 0
--------------------------------------------------
2025-03-18 01:01:45,697 - PythonTestLogger - ERROR - Test failed for QA7_P13_P14.py on QA7 for test case {'input': '4 5\n1 0 -1 2 3\n0 1 1 0 -1\n1 1 0 -1 4\n2 -1 3 1 0', 'expected': 'RREF =\n1.0 0.0 0.0 0.0 2.8\n0.0 1.0 0.0 0.0 0.5\n0.0 0.0 1.0 0.0 -1.5\n0.0 0.0 0.0 1.0 -0.7\n\nRank = 4\nNullity = 1\n', 'type': 'stdin'}

SRNs: P13/P14

Error:
Traceback (most recent call last):
  File "/Volumes/Aditya SSD/Project/AutomaticPythonTesting/AutomaticPythonTesting/scripts/QA7_P13_P14.py", line 3, in <module>
    from sympy import Matrix
ModuleNotFoundError: No module named 'sympy'


Test Type: stdin

Test Input:
4 5
1 0 -1 2 3
0 1 1 0 -1
1 1 0 -1 4
2 -1 3 1 0

Expected Output:
RREF =
1.0 0.0 0.0 0.0 2.8
0.0 1.0 0.0 0.0 0.5
0.0 0.0 1.0 0.0 -1.5
0.0 0.0 0.0 1.0 -0.7

Rank = 4
Nullity = 1

--------------------------------------------------
2025-03-18 01:01:45,994 - PythonTestLogger - ERROR - Test failed for QA8_P15_P16.py on QA8 for test case {'input': '2 2\n2 1\n3 4\n2 2\n5 6\n7 8', 'expected': 'C =\n2.6 3.2\n-0.2 -0.4\n\nRREF =\n1.0 0.0\n0.0 1.0\n\nRank = 2\nNullity = 0', 'type': 'stdin'}

SRNs: P15/P16

Error:
Traceback (most recent call last):
  File "/Volumes/Aditya SSD/Project/AutomaticPythonTesting/AutomaticPythonTesting/scripts/QA8_P15_P16.py", line 3, in <module>
    from sympy import Matrix
ModuleNotFoundError: No module named 'sympy'


Test Type: stdin

Test Input:
2 2
2 1
3 4
2 2
5 6
7 8

Expected Output:
C =
2.6 3.2
-0.2 -0.4

RREF =
1.0 0.0
0.0 1.0

Rank = 2
Nullity = 0
--------------------------------------------------
2025-03-18 01:01:46,273 - PythonTestLogger - ERROR - Test failed for QA8_P15_P16.py on QA8 for test case {'input': '3 3\n3 1 2\n4 2 1\n1 2 3\n3 2\n6 9\n3 7\n8 5\n', 'expected': 'C =\n0.2 2.2\n-0.4 -1.9\n2.8 2.2\n\nRREF =\n1.0 0.0 0.0\n0.0 1.0 0.0\n0.0 0.0 1.0\n\nRank = 3\nNullity = 0', 'type': 'stdin'}

SRNs: P15/P16

Error:
Traceback (most recent call last):
  File "/Volumes/Aditya SSD/Project/AutomaticPythonTesting/AutomaticPythonTesting/scripts/QA8_P15_P16.py", line 3, in <module>
    from sympy import Matrix
ModuleNotFoundError: No module named 'sympy'


Test Type: stdin

Test Input:
3 3
3 1 2
4 2 1
1 2 3
3 2
6 9
3 7
8 5


Expected Output:
C =
0.2 2.2
-0.4 -1.9
2.8 2.2

RREF =
1.0 0.0 0.0
0.0 1.0 0.0
0.0 0.0 1.0

Rank = 3
Nullity = 0
--------------------------------------------------
2025-03-18 01:01:46,557 - PythonTestLogger - ERROR - Test failed for QA8_P15_P16.py on QA8 for test case {'input': '4 4\n2 3 1 4\n1 5 3 2\n4 2 6 5\n3 1 2 3\n4 2\n5 6\n7 8\n9 10\n11 12', 'expected': 'C =\n7.3 7.8\n2.0 2.2\n-1.0 -1.1\n-3.7 -3.8\n\nRREF =\n1.0 0.0 0.0 0.0\n0.0 1.0 0.0 0.0\n0.0 0.0 1.0 0.0\n0.0 0.0 0.0 1.0\n\nRank = 4\nNullity = 0\n', 'type': 'stdin'}

SRNs: P15/P16

Error:
Traceback (most recent call last):
  File "/Volumes/Aditya SSD/Project/AutomaticPythonTesting/AutomaticPythonTesting/scripts/QA8_P15_P16.py", line 3, in <module>
    from sympy import Matrix
ModuleNotFoundError: No module named 'sympy'


Test Type: stdin

Test Input:
4 4
2 3 1 4
1 5 3 2
4 2 6 5
3 1 2 3
4 2
5 6
7 8
9 10
11 12

Expected Output:
C =
7.3 7.8
2.0 2.2
-1.0 -1.1
-3.7 -3.8

RREF =
1.0 0.0 0.0 0.0
0.0 1.0 0.0 0.0
0.0 0.0 1.0 0.0
0.0 0.0 0.0 1.0

Rank = 4
Nullity = 0

--------------------------------------------------
2025-03-18 01:01:47,652 - PythonTestLogger - ERROR - Test failed for QF5_P17_P18.py on QF5 for test case {'input': '2\n2 -1 1\n1 3 2', 'expected': 'U =\n1.0 -0.5 \n0.0 1.0 \n\nx =\n0.7 0.4', 'type': 'stdin'}

SRNs: P17/P18

Test Type: stdin

Test Input:
2
2 -1 1
1 3 2

Expected Output:
U =
1.0 -0.5 
0.0 1.0 

x =
0.7 0.4

Actual Output:
U =
1.0 -0.5
0.0 1.0

x =
0.7 0.4
--------------------------------------------------
2025-03-18 01:01:48,530 - PythonTestLogger - ERROR - Test failed for QF6_P19_P20.py on QF6 for test case {'input': '3 3\n1 2 -1\n2 4 -2\n3 6 -3', 'expected': 'RREF =\n1.0 2.0 -1.0\n0.0 0.0 0.0\n0.0 0.0 0.0', 'type': 'stdin'}

SRNs: P19/P20

Error:
Traceback (most recent call last):
  File "/Volumes/Aditya SSD/Project/AutomaticPythonTesting/AutomaticPythonTesting/scripts/QF6_P19_P20.py", line 3, in <module>
    from sympy import Matrix
ModuleNotFoundError: No module named 'sympy'


Test Type: stdin

Test Input:
3 3
1 2 -1
2 4 -2
3 6 -3

Expected Output:
RREF =
1.0 2.0 -1.0
0.0 0.0 0.0
0.0 0.0 0.0
--------------------------------------------------
2025-03-18 01:01:48,858 - PythonTestLogger - ERROR - Test failed for QF6_P19_P20.py on QF6 for test case {'input': '3 3\n1 2 3\n0 1 4\n5 6 0', 'expected': 'RREF =\n1.0 0.0 0.0\n0.0 1.0 0.0\n0.0 0.0 1.0', 'type': 'stdin'}

SRNs: P19/P20

Error:
Traceback (most recent call last):
  File "/Volumes/Aditya SSD/Project/AutomaticPythonTesting/AutomaticPythonTesting/scripts/QF6_P19_P20.py", line 3, in <module>
    from sympy import Matrix
ModuleNotFoundError: No module named 'sympy'


Test Type: stdin

Test Input:
3 3
1 2 3
0 1 4
5 6 0

Expected Output:
RREF =
1.0 0.0 0.0
0.0 1.0 0.0
0.0 0.0 1.0
--------------------------------------------------
2025-03-18 01:01:49,138 - PythonTestLogger - ERROR - Test failed for QF6_P19_P20.py on QF6 for test case {'input': '3 4\n4 7 2 5\n2 6 5 8\n1 3 1 4', 'expected': 'RREF =\n1.0 0.0 0.0 -2.6\n0.0 1.0 0.0 2.2\n0.0 0.0 1.0 0.0', 'type': 'stdin'}

SRNs: P19/P20

Error:
Traceback (most recent call last):
  File "/Volumes/Aditya SSD/Project/AutomaticPythonTesting/AutomaticPythonTesting/scripts/QF6_P19_P20.py", line 3, in <module>
    from sympy import Matrix
ModuleNotFoundError: No module named 'sympy'


Test Type: stdin

Test Input:
3 4
4 7 2 5
2 6 5 8
1 3 1 4

Expected Output:
RREF =
1.0 0.0 0.0 -2.6
0.0 1.0 0.0 2.2
0.0 0.0 1.0 0.0
--------------------------------------------------
2025-03-18 01:01:50,076 - PythonTestLogger - ERROR - Test failed for QA1_P1_P2.py on QA1 for test case {'input': '3\n2 -1 -2\n-4 6 3\n-4 -2 8\n3 7 10', 'expected': 'L =\n[[ 1.    0.    0.  ]\n [ 1.    1.    0.  ]\n [-0.5  -0.25  1.  ]]\n\nU =\n[[-4.    6.    3.  ]\n [ 0.   -8.    5.  ]\n [ 0.    0.    0.75]]\n\nx =\n26.62 9.92 16.67', 'type': 'stdin'}

SRNs: P1/P2

Test Type: stdin

Test Input:
3
2 -1 -2
-4 6 3
-4 -2 8
3 7 10

Expected Output:
L =
[[ 1.    0.    0.  ]
 [ 1.    1.    0.  ]
 [-0.5  -0.25  1.  ]]

U =
[[-4.    6.    3.  ]
 [ 0.   -8.    5.  ]
 [ 0.    0.    0.75]]

x =
26.62 9.92 16.67

Actual Output:
CHECK [[ 2. -1. -2.]
 [-4.  6.  3.]
 [-4. -2.  8.]]
L =
[[ 1.    0.    0.  ]
 [ 1.    1.    0.  ]
 [-0.5  -0.25  1.  ]]

U =
[[-4.    6.    3.  ]
 [ 0.   -8.    5.  ]
 [ 0.    0.    0.75]]

x =
26.62 9.92 16.67
--------------------------------------------------
2025-03-18 01:01:50,995 - PythonTestLogger - ERROR - Test failed for QA1_P1_P2.py on QA1 for test case {'input': '4\n4  1  0  2\n1  5  3 -1\n2  0  6  1\n3  2  1  7\n10 8 15 20', 'expected': 'L =\n[[ 1.    0.    0.    0.  ]\n [ 0.25  1.    0.    0.  ]\n [ 0.5  -0.11  1.    0.  ]\n [ 0.75  0.26  0.03  1.  ]]\n\nU =\n[[ 4.    1.    0.    2.  ]\n [ 0.    4.75  3.   -1.5 ]\n [ 0.    0.    6.32 -0.16]\n [ 0.    0.    0.    5.9 ]]\n\nx =\n1.43 0.64 1.72 1.81', 'type': 'stdin'}

SRNs: P1/P2

Test Type: stdin

Test Input:
4
4  1  0  2
1  5  3 -1
2  0  6  1
3  2  1  7
10 8 15 20

Expected Output:
L =
[[ 1.    0.    0.    0.  ]
 [ 0.25  1.    0.    0.  ]
 [ 0.5  -0.11  1.    0.  ]
 [ 0.75  0.26  0.03  1.  ]]

U =
[[ 4.    1.    0.    2.  ]
 [ 0.    4.75  3.   -1.5 ]
 [ 0.    0.    6.32 -0.16]
 [ 0.    0.    0.    5.9 ]]

x =
1.43 0.64 1.72 1.81

Actual Output:
CHECK [[ 4.  1.  0.  2.]
 [ 1.  5.  3. -1.]
 [ 2.  0.  6.  1.]
 [ 3.  2.  1.  7.]]
L =
[[ 1.    0.    0.    0.  ]
 [ 0.25  1.    0.    0.  ]
 [ 0.5  -0.11  1.    0.  ]
 [ 0.75  0.26  0.03  1.  ]]

U =
[[ 4.    1.    0.    2.  ]
 [ 0.    4.75  3.   -1.5 ]
 [ 0.    0.    6.32 -0.16]
 [ 0.    0.    0.    5.9 ]]

x =
1.43 0.64 1.72 1.81
--------------------------------------------------
2025-03-18 01:01:52,070 - PythonTestLogger - ERROR - Test failed for QA1_P1_P2.py on QA1 for test case {'input': '5\n5  2  1  0  3\n2  6  0  1 -1\n1  0  7  2  4\n0  1  2  8  0\n3 -1  4  0  9\n12 8 25 18 30', 'expected': 'L =\n[[ 1.    0.    0.    0.    0.  ]\n [ 0.4   1.    0.    0.    0.  ]\n [ 0.2  -0.08  1.    0.    0.  ]\n [ 0.    0.19  0.31  1.    0.  ]\n [ 0.6  -0.42  0.48 -0.08  1.  ]]\n\nU =\n[[ 5.    2.    1.    0.    3.  ]\n [ 0.    5.2  -0.4   1.   -2.2 ]\n [ 0.    0.    6.77  2.08  3.23]\n [ 0.    0.    0.    7.17 -0.57]\n [ 0.    0.    0.    0.    4.68]]\n\nx =\n-0.36 1.67 1.42 1.69 3.01', 'type': 'stdin'}

SRNs: P1/P2

Test Type: stdin

Test Input:
5
5  2  1  0  3
2  6  0  1 -1
1  0  7  2  4
0  1  2  8  0
3 -1  4  0  9
12 8 25 18 30

Expected Output:
L =
[[ 1.    0.    0.    0.    0.  ]
 [ 0.4   1.    0.    0.    0.  ]
 [ 0.2  -0.08  1.    0.    0.  ]
 [ 0.    0.19  0.31  1.    0.  ]
 [ 0.6  -0.42  0.48 -0.08  1.  ]]

U =
[[ 5.    2.    1.    0.    3.  ]
 [ 0.    5.2  -0.4   1.   -2.2 ]
 [ 0.    0.    6.77  2.08  3.23]
 [ 0.    0.    0.    7.17 -0.57]
 [ 0.    0.    0.    0.    4.68]]

x =
-0.36 1.67 1.42 1.69 3.01

Actual Output:
CHECK [[ 5.  2.  1.  0.  3.]
 [ 2.  6.  0.  1. -1.]
 [ 1.  0.  7.  2.  4.]
 [ 0.  1.  2.  8.  0.]
 [ 3. -1.  4.  0.  9.]]
L =
[[ 1.    0.    0.    0.    0.  ]
 [ 0.4   1.    0.    0.    0.  ]
 [ 0.2  -0.08  1.    0.    0.  ]
 [ 0.    0.19  0.31  1.    0.  ]
 [ 0.6  -0.42  0.48 -0.08  1.  ]]

U =
[[ 5.    2.    1.    0.    3.  ]
 [ 0.    5.2  -0.4   1.   -2.2 ]
 [ 0.    0.    6.77  2.08  3.23]
 [ 0.    0.    0.    7.17 -0.57]
 [ 0.    0.    0.    0.    4.68]]

x =
-0.36 1.67 1.42 1.69 3.01
--------------------------------------------------
